import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50 font-sans text-zinc-900 dark:bg-black dark:text-zinc-100">
        <div className="beauty-banner">
          <div className="beauty-banner__track">
            <span>Glow up season is here</span>
            <span>Free shipping on orders over $50</span>
            <span>New arrivals: serums, mists, and balms</span>
            <span>Glow up season is here</span>
            <span>Free shipping on orders over $50</span>
            <span>New arrivals: serums, mists, and balms</span>
          </div>
        </div>
        <header className="border-b border-pink-100 bg-pink-50/90 backdrop-blur dark:border-pink-900/40 dark:bg-pink-950/40">
          <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-4">
            <Link href="/" className="text-lg font-semibold tracking-tight">
              Beauty Store
            </Link>
            <nav className="flex items-center gap-6 text-sm font-medium">
              <Link
                href="/"
                className="text-zinc-700 transition hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100"
              >
                Home
              </Link>
              <Link
                href="/cart"
                className="text-zinc-700 transition hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100"
              >
                Cart
              </Link>
            </nav>
          </div>
        </header>

        <main className="flex-1">{children}</main>
        <footer className="border-t border-zinc-800 bg-gradient-to-br from-zinc-900 via-zinc-800 to-zinc-700">
          <div className="mx-auto w-full max-w-6xl px-6 py-6 text-sm text-zinc-600 dark:text-zinc-400">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <span>© {new Date().getFullYear()} Beauty Store</span>
              <div className="flex items-center gap-4">
                <Link
                  href="/"
                  className="transition hover:text-zinc-900 dark:hover:text-zinc-100"
                >
                  Privacy
                </Link>
                <Link
                  href="/"
                  className="transition hover:text-zinc-900 dark:hover:text-zinc-100"
                >
                  Terms
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
